nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  "@dnd-kit/core@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@dnd-kit/sortable@*":
    peerDependencies:
      react: "*"
      react-dom: "*" 